// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"WISE_SOFTWARE/DB/model"
)

func newHCV_old_seatstatus(db *gorm.DB, opts ...gen.DOOption) hCV_old_seatstatus {
	_hCV_old_seatstatus := hCV_old_seatstatus{}

	_hCV_old_seatstatus.hCV_old_seatstatusDo.UseDB(db, opts...)
	_hCV_old_seatstatus.hCV_old_seatstatusDo.UseModel(&model.HCV_old_seatstatus{})

	tableName := _hCV_old_seatstatus.hCV_old_seatstatusDo.TableName()
	_hCV_old_seatstatus.ALL = field.NewAsterisk(tableName)
	_hCV_old_seatstatus.STATUS = field.NewInt64(tableName, "STATUS")
	_hCV_old_seatstatus.NAME = field.NewString(tableName, "NAME")
	_hCV_old_seatstatus.ENNAME = field.NewString(tableName, "EN_NAME")
	_hCV_old_seatstatus.BOOKABLE = field.NewInt64(tableName, "BOOKABLE")
	_hCV_old_seatstatus.DISABLED = field.NewInt64(tableName, "DISABLED")

	_hCV_old_seatstatus.fillFieldMap()

	return _hCV_old_seatstatus
}

type hCV_old_seatstatus struct {
	hCV_old_seatstatusDo

	ALL      field.Asterisk
	STATUS   field.Int64
	NAME     field.String
	ENNAME   field.String
	BOOKABLE field.Int64
	DISABLED field.Int64

	fieldMap map[string]field.Expr
}

func (h hCV_old_seatstatus) Table(newTableName string) *hCV_old_seatstatus {
	h.hCV_old_seatstatusDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hCV_old_seatstatus) As(alias string) *hCV_old_seatstatus {
	h.hCV_old_seatstatusDo.DO = *(h.hCV_old_seatstatusDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hCV_old_seatstatus) updateTableName(table string) *hCV_old_seatstatus {
	h.ALL = field.NewAsterisk(table)
	h.STATUS = field.NewInt64(table, "STATUS")
	h.NAME = field.NewString(table, "NAME")
	h.ENNAME = field.NewString(table, "EN_NAME")
	h.BOOKABLE = field.NewInt64(table, "BOOKABLE")
	h.DISABLED = field.NewInt64(table, "DISABLED")

	h.fillFieldMap()

	return h
}

func (h *hCV_old_seatstatus) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hCV_old_seatstatus) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 5)
	h.fieldMap["STATUS"] = h.STATUS
	h.fieldMap["NAME"] = h.NAME
	h.fieldMap["EN_NAME"] = h.ENNAME
	h.fieldMap["BOOKABLE"] = h.BOOKABLE
	h.fieldMap["DISABLED"] = h.DISABLED
}

func (h hCV_old_seatstatus) clone(db *gorm.DB) hCV_old_seatstatus {
	h.hCV_old_seatstatusDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hCV_old_seatstatus) replaceDB(db *gorm.DB) hCV_old_seatstatus {
	h.hCV_old_seatstatusDo.ReplaceDB(db)
	return h
}

type hCV_old_seatstatusDo struct{ gen.DO }

type IHCV_old_seatstatusDo interface {
	gen.SubQuery
	Debug() IHCV_old_seatstatusDo
	WithContext(ctx context.Context) IHCV_old_seatstatusDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHCV_old_seatstatusDo
	WriteDB() IHCV_old_seatstatusDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHCV_old_seatstatusDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHCV_old_seatstatusDo
	Not(conds ...gen.Condition) IHCV_old_seatstatusDo
	Or(conds ...gen.Condition) IHCV_old_seatstatusDo
	Select(conds ...field.Expr) IHCV_old_seatstatusDo
	Where(conds ...gen.Condition) IHCV_old_seatstatusDo
	Order(conds ...field.Expr) IHCV_old_seatstatusDo
	Distinct(cols ...field.Expr) IHCV_old_seatstatusDo
	Omit(cols ...field.Expr) IHCV_old_seatstatusDo
	Join(table schema.Tabler, on ...field.Expr) IHCV_old_seatstatusDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_old_seatstatusDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHCV_old_seatstatusDo
	Group(cols ...field.Expr) IHCV_old_seatstatusDo
	Having(conds ...gen.Condition) IHCV_old_seatstatusDo
	Limit(limit int) IHCV_old_seatstatusDo
	Offset(offset int) IHCV_old_seatstatusDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_old_seatstatusDo
	Unscoped() IHCV_old_seatstatusDo
	Create(values ...*model.HCV_old_seatstatus) error
	CreateInBatches(values []*model.HCV_old_seatstatus, batchSize int) error
	Save(values ...*model.HCV_old_seatstatus) error
	First() (*model.HCV_old_seatstatus, error)
	Take() (*model.HCV_old_seatstatus, error)
	Last() (*model.HCV_old_seatstatus, error)
	Find() ([]*model.HCV_old_seatstatus, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_old_seatstatus, err error)
	FindInBatches(result *[]*model.HCV_old_seatstatus, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HCV_old_seatstatus) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHCV_old_seatstatusDo
	Assign(attrs ...field.AssignExpr) IHCV_old_seatstatusDo
	Joins(fields ...field.RelationField) IHCV_old_seatstatusDo
	Preload(fields ...field.RelationField) IHCV_old_seatstatusDo
	FirstOrInit() (*model.HCV_old_seatstatus, error)
	FirstOrCreate() (*model.HCV_old_seatstatus, error)
	FindByPage(offset int, limit int) (result []*model.HCV_old_seatstatus, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHCV_old_seatstatusDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hCV_old_seatstatusDo) Debug() IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Debug())
}

func (h hCV_old_seatstatusDo) WithContext(ctx context.Context) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hCV_old_seatstatusDo) ReadDB() IHCV_old_seatstatusDo {
	return h.Clauses(dbresolver.Read)
}

func (h hCV_old_seatstatusDo) WriteDB() IHCV_old_seatstatusDo {
	return h.Clauses(dbresolver.Write)
}

func (h hCV_old_seatstatusDo) Session(config *gorm.Session) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Session(config))
}

func (h hCV_old_seatstatusDo) Clauses(conds ...clause.Expression) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hCV_old_seatstatusDo) Returning(value interface{}, columns ...string) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hCV_old_seatstatusDo) Not(conds ...gen.Condition) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hCV_old_seatstatusDo) Or(conds ...gen.Condition) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hCV_old_seatstatusDo) Select(conds ...field.Expr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hCV_old_seatstatusDo) Where(conds ...gen.Condition) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hCV_old_seatstatusDo) Order(conds ...field.Expr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hCV_old_seatstatusDo) Distinct(cols ...field.Expr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hCV_old_seatstatusDo) Omit(cols ...field.Expr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hCV_old_seatstatusDo) Join(table schema.Tabler, on ...field.Expr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hCV_old_seatstatusDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hCV_old_seatstatusDo) RightJoin(table schema.Tabler, on ...field.Expr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hCV_old_seatstatusDo) Group(cols ...field.Expr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hCV_old_seatstatusDo) Having(conds ...gen.Condition) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hCV_old_seatstatusDo) Limit(limit int) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hCV_old_seatstatusDo) Offset(offset int) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hCV_old_seatstatusDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hCV_old_seatstatusDo) Unscoped() IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hCV_old_seatstatusDo) Create(values ...*model.HCV_old_seatstatus) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hCV_old_seatstatusDo) CreateInBatches(values []*model.HCV_old_seatstatus, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hCV_old_seatstatusDo) Save(values ...*model.HCV_old_seatstatus) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hCV_old_seatstatusDo) First() (*model.HCV_old_seatstatus, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_old_seatstatus), nil
	}
}

func (h hCV_old_seatstatusDo) Take() (*model.HCV_old_seatstatus, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_old_seatstatus), nil
	}
}

func (h hCV_old_seatstatusDo) Last() (*model.HCV_old_seatstatus, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_old_seatstatus), nil
	}
}

func (h hCV_old_seatstatusDo) Find() ([]*model.HCV_old_seatstatus, error) {
	result, err := h.DO.Find()
	return result.([]*model.HCV_old_seatstatus), err
}

func (h hCV_old_seatstatusDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_old_seatstatus, err error) {
	buf := make([]*model.HCV_old_seatstatus, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hCV_old_seatstatusDo) FindInBatches(result *[]*model.HCV_old_seatstatus, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hCV_old_seatstatusDo) Attrs(attrs ...field.AssignExpr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hCV_old_seatstatusDo) Assign(attrs ...field.AssignExpr) IHCV_old_seatstatusDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hCV_old_seatstatusDo) Joins(fields ...field.RelationField) IHCV_old_seatstatusDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hCV_old_seatstatusDo) Preload(fields ...field.RelationField) IHCV_old_seatstatusDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hCV_old_seatstatusDo) FirstOrInit() (*model.HCV_old_seatstatus, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_old_seatstatus), nil
	}
}

func (h hCV_old_seatstatusDo) FirstOrCreate() (*model.HCV_old_seatstatus, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_old_seatstatus), nil
	}
}

func (h hCV_old_seatstatusDo) FindByPage(offset int, limit int) (result []*model.HCV_old_seatstatus, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hCV_old_seatstatusDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hCV_old_seatstatusDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hCV_old_seatstatusDo) Delete(models ...*model.HCV_old_seatstatus) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hCV_old_seatstatusDo) withDO(do gen.Dao) *hCV_old_seatstatusDo {
	h.DO = *do.(*gen.DO)
	return h
}
