// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"WISE_SOFTWARE/DB/model"
)

func newHCV_patmast_view_ext(db *gorm.DB, opts ...gen.DOOption) hCV_patmast_view_ext {
	_hCV_patmast_view_ext := hCV_patmast_view_ext{}

	_hCV_patmast_view_ext.hCV_patmast_view_extDo.UseDB(db, opts...)
	_hCV_patmast_view_ext.hCV_patmast_view_extDo.UseModel(&model.HCV_patmast_view_ext{})

	tableName := _hCV_patmast_view_ext.hCV_patmast_view_extDo.TableName()
	_hCV_patmast_view_ext.ALL = field.NewAsterisk(tableName)
	_hCV_patmast_view_ext.AltPid = field.NewString(tableName, "alt_pid")
	_hCV_patmast_view_ext.PatType = field.NewString(tableName, "pat_type")
	_hCV_patmast_view_ext.DeptCode = field.NewString(tableName, "dept_code")
	_hCV_patmast_view_ext.CardIssueCnt = field.NewInt64(tableName, "card_issue_cnt")
	_hCV_patmast_view_ext.DateExprd = field.NewString(tableName, "date_exprd")
	_hCV_patmast_view_ext.Username = field.NewString(tableName, "username")
	_hCV_patmast_view_ext.Phone3 = field.NewString(tableName, "phone3")

	_hCV_patmast_view_ext.fillFieldMap()

	return _hCV_patmast_view_ext
}

type hCV_patmast_view_ext struct {
	hCV_patmast_view_extDo

	ALL          field.Asterisk
	AltPid       field.String
	PatType      field.String
	DeptCode     field.String
	CardIssueCnt field.Int64
	DateExprd    field.String
	Username     field.String
	Phone3       field.String

	fieldMap map[string]field.Expr
}

func (h hCV_patmast_view_ext) Table(newTableName string) *hCV_patmast_view_ext {
	h.hCV_patmast_view_extDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hCV_patmast_view_ext) As(alias string) *hCV_patmast_view_ext {
	h.hCV_patmast_view_extDo.DO = *(h.hCV_patmast_view_extDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hCV_patmast_view_ext) updateTableName(table string) *hCV_patmast_view_ext {
	h.ALL = field.NewAsterisk(table)
	h.AltPid = field.NewString(table, "alt_pid")
	h.PatType = field.NewString(table, "pat_type")
	h.DeptCode = field.NewString(table, "dept_code")
	h.CardIssueCnt = field.NewInt64(table, "card_issue_cnt")
	h.DateExprd = field.NewString(table, "date_exprd")
	h.Username = field.NewString(table, "username")
	h.Phone3 = field.NewString(table, "phone3")

	h.fillFieldMap()

	return h
}

func (h *hCV_patmast_view_ext) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hCV_patmast_view_ext) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 7)
	h.fieldMap["alt_pid"] = h.AltPid
	h.fieldMap["pat_type"] = h.PatType
	h.fieldMap["dept_code"] = h.DeptCode
	h.fieldMap["card_issue_cnt"] = h.CardIssueCnt
	h.fieldMap["date_exprd"] = h.DateExprd
	h.fieldMap["username"] = h.Username
	h.fieldMap["phone3"] = h.Phone3
}

func (h hCV_patmast_view_ext) clone(db *gorm.DB) hCV_patmast_view_ext {
	h.hCV_patmast_view_extDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hCV_patmast_view_ext) replaceDB(db *gorm.DB) hCV_patmast_view_ext {
	h.hCV_patmast_view_extDo.ReplaceDB(db)
	return h
}

type hCV_patmast_view_extDo struct{ gen.DO }

type IHCV_patmast_view_extDo interface {
	gen.SubQuery
	Debug() IHCV_patmast_view_extDo
	WithContext(ctx context.Context) IHCV_patmast_view_extDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHCV_patmast_view_extDo
	WriteDB() IHCV_patmast_view_extDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHCV_patmast_view_extDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHCV_patmast_view_extDo
	Not(conds ...gen.Condition) IHCV_patmast_view_extDo
	Or(conds ...gen.Condition) IHCV_patmast_view_extDo
	Select(conds ...field.Expr) IHCV_patmast_view_extDo
	Where(conds ...gen.Condition) IHCV_patmast_view_extDo
	Order(conds ...field.Expr) IHCV_patmast_view_extDo
	Distinct(cols ...field.Expr) IHCV_patmast_view_extDo
	Omit(cols ...field.Expr) IHCV_patmast_view_extDo
	Join(table schema.Tabler, on ...field.Expr) IHCV_patmast_view_extDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_patmast_view_extDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHCV_patmast_view_extDo
	Group(cols ...field.Expr) IHCV_patmast_view_extDo
	Having(conds ...gen.Condition) IHCV_patmast_view_extDo
	Limit(limit int) IHCV_patmast_view_extDo
	Offset(offset int) IHCV_patmast_view_extDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_patmast_view_extDo
	Unscoped() IHCV_patmast_view_extDo
	Create(values ...*model.HCV_patmast_view_ext) error
	CreateInBatches(values []*model.HCV_patmast_view_ext, batchSize int) error
	Save(values ...*model.HCV_patmast_view_ext) error
	First() (*model.HCV_patmast_view_ext, error)
	Take() (*model.HCV_patmast_view_ext, error)
	Last() (*model.HCV_patmast_view_ext, error)
	Find() ([]*model.HCV_patmast_view_ext, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_patmast_view_ext, err error)
	FindInBatches(result *[]*model.HCV_patmast_view_ext, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HCV_patmast_view_ext) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHCV_patmast_view_extDo
	Assign(attrs ...field.AssignExpr) IHCV_patmast_view_extDo
	Joins(fields ...field.RelationField) IHCV_patmast_view_extDo
	Preload(fields ...field.RelationField) IHCV_patmast_view_extDo
	FirstOrInit() (*model.HCV_patmast_view_ext, error)
	FirstOrCreate() (*model.HCV_patmast_view_ext, error)
	FindByPage(offset int, limit int) (result []*model.HCV_patmast_view_ext, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHCV_patmast_view_extDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hCV_patmast_view_extDo) Debug() IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Debug())
}

func (h hCV_patmast_view_extDo) WithContext(ctx context.Context) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hCV_patmast_view_extDo) ReadDB() IHCV_patmast_view_extDo {
	return h.Clauses(dbresolver.Read)
}

func (h hCV_patmast_view_extDo) WriteDB() IHCV_patmast_view_extDo {
	return h.Clauses(dbresolver.Write)
}

func (h hCV_patmast_view_extDo) Session(config *gorm.Session) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Session(config))
}

func (h hCV_patmast_view_extDo) Clauses(conds ...clause.Expression) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hCV_patmast_view_extDo) Returning(value interface{}, columns ...string) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hCV_patmast_view_extDo) Not(conds ...gen.Condition) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hCV_patmast_view_extDo) Or(conds ...gen.Condition) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hCV_patmast_view_extDo) Select(conds ...field.Expr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hCV_patmast_view_extDo) Where(conds ...gen.Condition) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hCV_patmast_view_extDo) Order(conds ...field.Expr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hCV_patmast_view_extDo) Distinct(cols ...field.Expr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hCV_patmast_view_extDo) Omit(cols ...field.Expr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hCV_patmast_view_extDo) Join(table schema.Tabler, on ...field.Expr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hCV_patmast_view_extDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hCV_patmast_view_extDo) RightJoin(table schema.Tabler, on ...field.Expr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hCV_patmast_view_extDo) Group(cols ...field.Expr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hCV_patmast_view_extDo) Having(conds ...gen.Condition) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hCV_patmast_view_extDo) Limit(limit int) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hCV_patmast_view_extDo) Offset(offset int) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hCV_patmast_view_extDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hCV_patmast_view_extDo) Unscoped() IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hCV_patmast_view_extDo) Create(values ...*model.HCV_patmast_view_ext) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hCV_patmast_view_extDo) CreateInBatches(values []*model.HCV_patmast_view_ext, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hCV_patmast_view_extDo) Save(values ...*model.HCV_patmast_view_ext) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hCV_patmast_view_extDo) First() (*model.HCV_patmast_view_ext, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_patmast_view_ext), nil
	}
}

func (h hCV_patmast_view_extDo) Take() (*model.HCV_patmast_view_ext, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_patmast_view_ext), nil
	}
}

func (h hCV_patmast_view_extDo) Last() (*model.HCV_patmast_view_ext, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_patmast_view_ext), nil
	}
}

func (h hCV_patmast_view_extDo) Find() ([]*model.HCV_patmast_view_ext, error) {
	result, err := h.DO.Find()
	return result.([]*model.HCV_patmast_view_ext), err
}

func (h hCV_patmast_view_extDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_patmast_view_ext, err error) {
	buf := make([]*model.HCV_patmast_view_ext, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hCV_patmast_view_extDo) FindInBatches(result *[]*model.HCV_patmast_view_ext, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hCV_patmast_view_extDo) Attrs(attrs ...field.AssignExpr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hCV_patmast_view_extDo) Assign(attrs ...field.AssignExpr) IHCV_patmast_view_extDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hCV_patmast_view_extDo) Joins(fields ...field.RelationField) IHCV_patmast_view_extDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hCV_patmast_view_extDo) Preload(fields ...field.RelationField) IHCV_patmast_view_extDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hCV_patmast_view_extDo) FirstOrInit() (*model.HCV_patmast_view_ext, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_patmast_view_ext), nil
	}
}

func (h hCV_patmast_view_extDo) FirstOrCreate() (*model.HCV_patmast_view_ext, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_patmast_view_ext), nil
	}
}

func (h hCV_patmast_view_extDo) FindByPage(offset int, limit int) (result []*model.HCV_patmast_view_ext, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hCV_patmast_view_extDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hCV_patmast_view_extDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hCV_patmast_view_extDo) Delete(models ...*model.HCV_patmast_view_ext) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hCV_patmast_view_extDo) withDO(do gen.Dao) *hCV_patmast_view_extDo {
	h.DO = *do.(*gen.DO)
	return h
}
