// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"WISE_SOFTWARE/DB/model"
)

func newHCV_TV_YESTERDAY_USE_TIME(db *gorm.DB, opts ...gen.DOOption) hCV_TV_YESTERDAY_USE_TIME {
	_hCV_TV_YESTERDAY_USE_TIME := hCV_TV_YESTERDAY_USE_TIME{}

	_hCV_TV_YESTERDAY_USE_TIME.hCV_TV_YESTERDAY_USE_TIMEDo.UseDB(db, opts...)
	_hCV_TV_YESTERDAY_USE_TIME.hCV_TV_YESTERDAY_USE_TIMEDo.UseModel(&model.HCV_TV_YESTERDAY_USE_TIME{})

	tableName := _hCV_TV_YESTERDAY_USE_TIME.hCV_TV_YESTERDAY_USE_TIMEDo.TableName()
	_hCV_TV_YESTERDAY_USE_TIME.ALL = field.NewAsterisk(tableName)
	_hCV_TV_YESTERDAY_USE_TIME.Libno = field.NewInt64(tableName, "libno")
	_hCV_TV_YESTERDAY_USE_TIME.UseDate = field.NewString(tableName, "use_date")
	_hCV_TV_YESTERDAY_USE_TIME.StartTime = field.NewString(tableName, "start_time")
	_hCV_TV_YESTERDAY_USE_TIME.EndTime = field.NewString(tableName, "end_time")
	_hCV_TV_YESTERDAY_USE_TIME.STARTTIME = field.NewTime(tableName, "STARTTIME")
	_hCV_TV_YESTERDAY_USE_TIME.RETURNTIME = field.NewTime(tableName, "RETURNTIME")
	_hCV_TV_YESTERDAY_USE_TIME.STATUS = field.NewInt64(tableName, "STATUS")
	_hCV_TV_YESTERDAY_USE_TIME.Gubun = field.NewInt64(tableName, "gubun")

	_hCV_TV_YESTERDAY_USE_TIME.fillFieldMap()

	return _hCV_TV_YESTERDAY_USE_TIME
}

type hCV_TV_YESTERDAY_USE_TIME struct {
	hCV_TV_YESTERDAY_USE_TIMEDo

	ALL        field.Asterisk
	Libno      field.Int64
	UseDate    field.String
	StartTime  field.String
	EndTime    field.String
	STARTTIME  field.Time
	RETURNTIME field.Time
	STATUS     field.Int64
	Gubun      field.Int64

	fieldMap map[string]field.Expr
}

func (h hCV_TV_YESTERDAY_USE_TIME) Table(newTableName string) *hCV_TV_YESTERDAY_USE_TIME {
	h.hCV_TV_YESTERDAY_USE_TIMEDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hCV_TV_YESTERDAY_USE_TIME) As(alias string) *hCV_TV_YESTERDAY_USE_TIME {
	h.hCV_TV_YESTERDAY_USE_TIMEDo.DO = *(h.hCV_TV_YESTERDAY_USE_TIMEDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hCV_TV_YESTERDAY_USE_TIME) updateTableName(table string) *hCV_TV_YESTERDAY_USE_TIME {
	h.ALL = field.NewAsterisk(table)
	h.Libno = field.NewInt64(table, "libno")
	h.UseDate = field.NewString(table, "use_date")
	h.StartTime = field.NewString(table, "start_time")
	h.EndTime = field.NewString(table, "end_time")
	h.STARTTIME = field.NewTime(table, "STARTTIME")
	h.RETURNTIME = field.NewTime(table, "RETURNTIME")
	h.STATUS = field.NewInt64(table, "STATUS")
	h.Gubun = field.NewInt64(table, "gubun")

	h.fillFieldMap()

	return h
}

func (h *hCV_TV_YESTERDAY_USE_TIME) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hCV_TV_YESTERDAY_USE_TIME) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 8)
	h.fieldMap["libno"] = h.Libno
	h.fieldMap["use_date"] = h.UseDate
	h.fieldMap["start_time"] = h.StartTime
	h.fieldMap["end_time"] = h.EndTime
	h.fieldMap["STARTTIME"] = h.STARTTIME
	h.fieldMap["RETURNTIME"] = h.RETURNTIME
	h.fieldMap["STATUS"] = h.STATUS
	h.fieldMap["gubun"] = h.Gubun
}

func (h hCV_TV_YESTERDAY_USE_TIME) clone(db *gorm.DB) hCV_TV_YESTERDAY_USE_TIME {
	h.hCV_TV_YESTERDAY_USE_TIMEDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hCV_TV_YESTERDAY_USE_TIME) replaceDB(db *gorm.DB) hCV_TV_YESTERDAY_USE_TIME {
	h.hCV_TV_YESTERDAY_USE_TIMEDo.ReplaceDB(db)
	return h
}

type hCV_TV_YESTERDAY_USE_TIMEDo struct{ gen.DO }

type IHCV_TV_YESTERDAY_USE_TIMEDo interface {
	gen.SubQuery
	Debug() IHCV_TV_YESTERDAY_USE_TIMEDo
	WithContext(ctx context.Context) IHCV_TV_YESTERDAY_USE_TIMEDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHCV_TV_YESTERDAY_USE_TIMEDo
	WriteDB() IHCV_TV_YESTERDAY_USE_TIMEDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHCV_TV_YESTERDAY_USE_TIMEDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHCV_TV_YESTERDAY_USE_TIMEDo
	Not(conds ...gen.Condition) IHCV_TV_YESTERDAY_USE_TIMEDo
	Or(conds ...gen.Condition) IHCV_TV_YESTERDAY_USE_TIMEDo
	Select(conds ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo
	Where(conds ...gen.Condition) IHCV_TV_YESTERDAY_USE_TIMEDo
	Order(conds ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo
	Distinct(cols ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo
	Omit(cols ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo
	Join(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo
	Group(cols ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo
	Having(conds ...gen.Condition) IHCV_TV_YESTERDAY_USE_TIMEDo
	Limit(limit int) IHCV_TV_YESTERDAY_USE_TIMEDo
	Offset(offset int) IHCV_TV_YESTERDAY_USE_TIMEDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_TV_YESTERDAY_USE_TIMEDo
	Unscoped() IHCV_TV_YESTERDAY_USE_TIMEDo
	Create(values ...*model.HCV_TV_YESTERDAY_USE_TIME) error
	CreateInBatches(values []*model.HCV_TV_YESTERDAY_USE_TIME, batchSize int) error
	Save(values ...*model.HCV_TV_YESTERDAY_USE_TIME) error
	First() (*model.HCV_TV_YESTERDAY_USE_TIME, error)
	Take() (*model.HCV_TV_YESTERDAY_USE_TIME, error)
	Last() (*model.HCV_TV_YESTERDAY_USE_TIME, error)
	Find() ([]*model.HCV_TV_YESTERDAY_USE_TIME, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_TV_YESTERDAY_USE_TIME, err error)
	FindInBatches(result *[]*model.HCV_TV_YESTERDAY_USE_TIME, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HCV_TV_YESTERDAY_USE_TIME) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHCV_TV_YESTERDAY_USE_TIMEDo
	Assign(attrs ...field.AssignExpr) IHCV_TV_YESTERDAY_USE_TIMEDo
	Joins(fields ...field.RelationField) IHCV_TV_YESTERDAY_USE_TIMEDo
	Preload(fields ...field.RelationField) IHCV_TV_YESTERDAY_USE_TIMEDo
	FirstOrInit() (*model.HCV_TV_YESTERDAY_USE_TIME, error)
	FirstOrCreate() (*model.HCV_TV_YESTERDAY_USE_TIME, error)
	FindByPage(offset int, limit int) (result []*model.HCV_TV_YESTERDAY_USE_TIME, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHCV_TV_YESTERDAY_USE_TIMEDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Debug() IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Debug())
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) WithContext(ctx context.Context) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) ReadDB() IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.Clauses(dbresolver.Read)
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) WriteDB() IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.Clauses(dbresolver.Write)
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Session(config *gorm.Session) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Session(config))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Clauses(conds ...clause.Expression) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Returning(value interface{}, columns ...string) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Not(conds ...gen.Condition) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Or(conds ...gen.Condition) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Select(conds ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Where(conds ...gen.Condition) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Order(conds ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Distinct(cols ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Omit(cols ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Join(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) RightJoin(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Group(cols ...field.Expr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Having(conds ...gen.Condition) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Limit(limit int) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Offset(offset int) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Unscoped() IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Create(values ...*model.HCV_TV_YESTERDAY_USE_TIME) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) CreateInBatches(values []*model.HCV_TV_YESTERDAY_USE_TIME, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hCV_TV_YESTERDAY_USE_TIMEDo) Save(values ...*model.HCV_TV_YESTERDAY_USE_TIME) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) First() (*model.HCV_TV_YESTERDAY_USE_TIME, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_USE_TIME), nil
	}
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Take() (*model.HCV_TV_YESTERDAY_USE_TIME, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_USE_TIME), nil
	}
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Last() (*model.HCV_TV_YESTERDAY_USE_TIME, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_USE_TIME), nil
	}
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Find() ([]*model.HCV_TV_YESTERDAY_USE_TIME, error) {
	result, err := h.DO.Find()
	return result.([]*model.HCV_TV_YESTERDAY_USE_TIME), err
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_TV_YESTERDAY_USE_TIME, err error) {
	buf := make([]*model.HCV_TV_YESTERDAY_USE_TIME, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) FindInBatches(result *[]*model.HCV_TV_YESTERDAY_USE_TIME, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Attrs(attrs ...field.AssignExpr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Assign(attrs ...field.AssignExpr) IHCV_TV_YESTERDAY_USE_TIMEDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Joins(fields ...field.RelationField) IHCV_TV_YESTERDAY_USE_TIMEDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Preload(fields ...field.RelationField) IHCV_TV_YESTERDAY_USE_TIMEDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) FirstOrInit() (*model.HCV_TV_YESTERDAY_USE_TIME, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_USE_TIME), nil
	}
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) FirstOrCreate() (*model.HCV_TV_YESTERDAY_USE_TIME, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_USE_TIME), nil
	}
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) FindByPage(offset int, limit int) (result []*model.HCV_TV_YESTERDAY_USE_TIME, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hCV_TV_YESTERDAY_USE_TIMEDo) Delete(models ...*model.HCV_TV_YESTERDAY_USE_TIME) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hCV_TV_YESTERDAY_USE_TIMEDo) withDO(do gen.Dao) *hCV_TV_YESTERDAY_USE_TIMEDo {
	h.DO = *do.(*gen.DO)
	return h
}
