// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"WISE_SOFTWARE/DB/model"
)

func newHCV_TV_YESTERDAY_PAT(db *gorm.DB, opts ...gen.DOOption) hCV_TV_YESTERDAY_PAT {
	_hCV_TV_YESTERDAY_PAT := hCV_TV_YESTERDAY_PAT{}

	_hCV_TV_YESTERDAY_PAT.hCV_TV_YESTERDAY_PATDo.UseDB(db, opts...)
	_hCV_TV_YESTERDAY_PAT.hCV_TV_YESTERDAY_PATDo.UseModel(&model.HCV_TV_YESTERDAY_PAT{})

	tableName := _hCV_TV_YESTERDAY_PAT.hCV_TV_YESTERDAY_PATDo.TableName()
	_hCV_TV_YESTERDAY_PAT.ALL = field.NewAsterisk(tableName)
	_hCV_TV_YESTERDAY_PAT.UserPosition = field.NewString(tableName, "user_position")
	_hCV_TV_YESTERDAY_PAT.PositionName = field.NewString(tableName, "position_name")
	_hCV_TV_YESTERDAY_PAT.UseCnt = field.NewInt64(tableName, "use_cnt")
	_hCV_TV_YESTERDAY_PAT.Libno = field.NewInt64(tableName, "libno")
	_hCV_TV_YESTERDAY_PAT.DISPORDER = field.NewInt64(tableName, "DISP_ORDER")

	_hCV_TV_YESTERDAY_PAT.fillFieldMap()

	return _hCV_TV_YESTERDAY_PAT
}

type hCV_TV_YESTERDAY_PAT struct {
	hCV_TV_YESTERDAY_PATDo

	ALL          field.Asterisk
	UserPosition field.String
	PositionName field.String
	UseCnt       field.Int64
	Libno        field.Int64
	DISPORDER    field.Int64

	fieldMap map[string]field.Expr
}

func (h hCV_TV_YESTERDAY_PAT) Table(newTableName string) *hCV_TV_YESTERDAY_PAT {
	h.hCV_TV_YESTERDAY_PATDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hCV_TV_YESTERDAY_PAT) As(alias string) *hCV_TV_YESTERDAY_PAT {
	h.hCV_TV_YESTERDAY_PATDo.DO = *(h.hCV_TV_YESTERDAY_PATDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hCV_TV_YESTERDAY_PAT) updateTableName(table string) *hCV_TV_YESTERDAY_PAT {
	h.ALL = field.NewAsterisk(table)
	h.UserPosition = field.NewString(table, "user_position")
	h.PositionName = field.NewString(table, "position_name")
	h.UseCnt = field.NewInt64(table, "use_cnt")
	h.Libno = field.NewInt64(table, "libno")
	h.DISPORDER = field.NewInt64(table, "DISP_ORDER")

	h.fillFieldMap()

	return h
}

func (h *hCV_TV_YESTERDAY_PAT) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hCV_TV_YESTERDAY_PAT) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 5)
	h.fieldMap["user_position"] = h.UserPosition
	h.fieldMap["position_name"] = h.PositionName
	h.fieldMap["use_cnt"] = h.UseCnt
	h.fieldMap["libno"] = h.Libno
	h.fieldMap["DISP_ORDER"] = h.DISPORDER
}

func (h hCV_TV_YESTERDAY_PAT) clone(db *gorm.DB) hCV_TV_YESTERDAY_PAT {
	h.hCV_TV_YESTERDAY_PATDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hCV_TV_YESTERDAY_PAT) replaceDB(db *gorm.DB) hCV_TV_YESTERDAY_PAT {
	h.hCV_TV_YESTERDAY_PATDo.ReplaceDB(db)
	return h
}

type hCV_TV_YESTERDAY_PATDo struct{ gen.DO }

type IHCV_TV_YESTERDAY_PATDo interface {
	gen.SubQuery
	Debug() IHCV_TV_YESTERDAY_PATDo
	WithContext(ctx context.Context) IHCV_TV_YESTERDAY_PATDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHCV_TV_YESTERDAY_PATDo
	WriteDB() IHCV_TV_YESTERDAY_PATDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHCV_TV_YESTERDAY_PATDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHCV_TV_YESTERDAY_PATDo
	Not(conds ...gen.Condition) IHCV_TV_YESTERDAY_PATDo
	Or(conds ...gen.Condition) IHCV_TV_YESTERDAY_PATDo
	Select(conds ...field.Expr) IHCV_TV_YESTERDAY_PATDo
	Where(conds ...gen.Condition) IHCV_TV_YESTERDAY_PATDo
	Order(conds ...field.Expr) IHCV_TV_YESTERDAY_PATDo
	Distinct(cols ...field.Expr) IHCV_TV_YESTERDAY_PATDo
	Omit(cols ...field.Expr) IHCV_TV_YESTERDAY_PATDo
	Join(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_PATDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_PATDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_PATDo
	Group(cols ...field.Expr) IHCV_TV_YESTERDAY_PATDo
	Having(conds ...gen.Condition) IHCV_TV_YESTERDAY_PATDo
	Limit(limit int) IHCV_TV_YESTERDAY_PATDo
	Offset(offset int) IHCV_TV_YESTERDAY_PATDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_TV_YESTERDAY_PATDo
	Unscoped() IHCV_TV_YESTERDAY_PATDo
	Create(values ...*model.HCV_TV_YESTERDAY_PAT) error
	CreateInBatches(values []*model.HCV_TV_YESTERDAY_PAT, batchSize int) error
	Save(values ...*model.HCV_TV_YESTERDAY_PAT) error
	First() (*model.HCV_TV_YESTERDAY_PAT, error)
	Take() (*model.HCV_TV_YESTERDAY_PAT, error)
	Last() (*model.HCV_TV_YESTERDAY_PAT, error)
	Find() ([]*model.HCV_TV_YESTERDAY_PAT, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_TV_YESTERDAY_PAT, err error)
	FindInBatches(result *[]*model.HCV_TV_YESTERDAY_PAT, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HCV_TV_YESTERDAY_PAT) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHCV_TV_YESTERDAY_PATDo
	Assign(attrs ...field.AssignExpr) IHCV_TV_YESTERDAY_PATDo
	Joins(fields ...field.RelationField) IHCV_TV_YESTERDAY_PATDo
	Preload(fields ...field.RelationField) IHCV_TV_YESTERDAY_PATDo
	FirstOrInit() (*model.HCV_TV_YESTERDAY_PAT, error)
	FirstOrCreate() (*model.HCV_TV_YESTERDAY_PAT, error)
	FindByPage(offset int, limit int) (result []*model.HCV_TV_YESTERDAY_PAT, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHCV_TV_YESTERDAY_PATDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hCV_TV_YESTERDAY_PATDo) Debug() IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Debug())
}

func (h hCV_TV_YESTERDAY_PATDo) WithContext(ctx context.Context) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hCV_TV_YESTERDAY_PATDo) ReadDB() IHCV_TV_YESTERDAY_PATDo {
	return h.Clauses(dbresolver.Read)
}

func (h hCV_TV_YESTERDAY_PATDo) WriteDB() IHCV_TV_YESTERDAY_PATDo {
	return h.Clauses(dbresolver.Write)
}

func (h hCV_TV_YESTERDAY_PATDo) Session(config *gorm.Session) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Session(config))
}

func (h hCV_TV_YESTERDAY_PATDo) Clauses(conds ...clause.Expression) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hCV_TV_YESTERDAY_PATDo) Returning(value interface{}, columns ...string) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hCV_TV_YESTERDAY_PATDo) Not(conds ...gen.Condition) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hCV_TV_YESTERDAY_PATDo) Or(conds ...gen.Condition) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hCV_TV_YESTERDAY_PATDo) Select(conds ...field.Expr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hCV_TV_YESTERDAY_PATDo) Where(conds ...gen.Condition) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hCV_TV_YESTERDAY_PATDo) Order(conds ...field.Expr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hCV_TV_YESTERDAY_PATDo) Distinct(cols ...field.Expr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hCV_TV_YESTERDAY_PATDo) Omit(cols ...field.Expr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hCV_TV_YESTERDAY_PATDo) Join(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hCV_TV_YESTERDAY_PATDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hCV_TV_YESTERDAY_PATDo) RightJoin(table schema.Tabler, on ...field.Expr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hCV_TV_YESTERDAY_PATDo) Group(cols ...field.Expr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hCV_TV_YESTERDAY_PATDo) Having(conds ...gen.Condition) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hCV_TV_YESTERDAY_PATDo) Limit(limit int) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hCV_TV_YESTERDAY_PATDo) Offset(offset int) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hCV_TV_YESTERDAY_PATDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hCV_TV_YESTERDAY_PATDo) Unscoped() IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hCV_TV_YESTERDAY_PATDo) Create(values ...*model.HCV_TV_YESTERDAY_PAT) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hCV_TV_YESTERDAY_PATDo) CreateInBatches(values []*model.HCV_TV_YESTERDAY_PAT, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hCV_TV_YESTERDAY_PATDo) Save(values ...*model.HCV_TV_YESTERDAY_PAT) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hCV_TV_YESTERDAY_PATDo) First() (*model.HCV_TV_YESTERDAY_PAT, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_PAT), nil
	}
}

func (h hCV_TV_YESTERDAY_PATDo) Take() (*model.HCV_TV_YESTERDAY_PAT, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_PAT), nil
	}
}

func (h hCV_TV_YESTERDAY_PATDo) Last() (*model.HCV_TV_YESTERDAY_PAT, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_PAT), nil
	}
}

func (h hCV_TV_YESTERDAY_PATDo) Find() ([]*model.HCV_TV_YESTERDAY_PAT, error) {
	result, err := h.DO.Find()
	return result.([]*model.HCV_TV_YESTERDAY_PAT), err
}

func (h hCV_TV_YESTERDAY_PATDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_TV_YESTERDAY_PAT, err error) {
	buf := make([]*model.HCV_TV_YESTERDAY_PAT, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hCV_TV_YESTERDAY_PATDo) FindInBatches(result *[]*model.HCV_TV_YESTERDAY_PAT, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hCV_TV_YESTERDAY_PATDo) Attrs(attrs ...field.AssignExpr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hCV_TV_YESTERDAY_PATDo) Assign(attrs ...field.AssignExpr) IHCV_TV_YESTERDAY_PATDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hCV_TV_YESTERDAY_PATDo) Joins(fields ...field.RelationField) IHCV_TV_YESTERDAY_PATDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hCV_TV_YESTERDAY_PATDo) Preload(fields ...field.RelationField) IHCV_TV_YESTERDAY_PATDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hCV_TV_YESTERDAY_PATDo) FirstOrInit() (*model.HCV_TV_YESTERDAY_PAT, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_PAT), nil
	}
}

func (h hCV_TV_YESTERDAY_PATDo) FirstOrCreate() (*model.HCV_TV_YESTERDAY_PAT, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_TV_YESTERDAY_PAT), nil
	}
}

func (h hCV_TV_YESTERDAY_PATDo) FindByPage(offset int, limit int) (result []*model.HCV_TV_YESTERDAY_PAT, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hCV_TV_YESTERDAY_PATDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hCV_TV_YESTERDAY_PATDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hCV_TV_YESTERDAY_PATDo) Delete(models ...*model.HCV_TV_YESTERDAY_PAT) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hCV_TV_YESTERDAY_PATDo) withDO(do gen.Dao) *hCV_TV_YESTERDAY_PATDo {
	h.DO = *do.(*gen.DO)
	return h
}
