// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"WISE_SOFTWARE/DB/model"
)

func newHCV_VIEW_SECTOR_USING_COUNT(db *gorm.DB, opts ...gen.DOOption) hCV_VIEW_SECTOR_USING_COUNT {
	_hCV_VIEW_SECTOR_USING_COUNT := hCV_VIEW_SECTOR_USING_COUNT{}

	_hCV_VIEW_SECTOR_USING_COUNT.hCV_VIEW_SECTOR_USING_COUNTDo.UseDB(db, opts...)
	_hCV_VIEW_SECTOR_USING_COUNT.hCV_VIEW_SECTOR_USING_COUNTDo.UseModel(&model.HCV_VIEW_SECTOR_USING_COUNT{})

	tableName := _hCV_VIEW_SECTOR_USING_COUNT.hCV_VIEW_SECTOR_USING_COUNTDo.TableName()
	_hCV_VIEW_SECTOR_USING_COUNT.ALL = field.NewAsterisk(tableName)
	_hCV_VIEW_SECTOR_USING_COUNT.LIBNAME = field.NewString(tableName, "LIB_NAME")
	_hCV_VIEW_SECTOR_USING_COUNT.LIBENNAME = field.NewString(tableName, "LIB_EN_NAME")
	_hCV_VIEW_SECTOR_USING_COUNT.FLOORNAME = field.NewString(tableName, "FLOOR_NAME")
	_hCV_VIEW_SECTOR_USING_COUNT.FLOORENNAME = field.NewString(tableName, "FLOOR_EN_NAME")
	_hCV_VIEW_SECTOR_USING_COUNT.ROOMNAME = field.NewString(tableName, "ROOM_NAME")
	_hCV_VIEW_SECTOR_USING_COUNT.ROOMENNAME = field.NewString(tableName, "ROOM_EN_NAME")
	_hCV_VIEW_SECTOR_USING_COUNT.SECTORNAME = field.NewString(tableName, "SECTOR_NAME")
	_hCV_VIEW_SECTOR_USING_COUNT.SECTORENNAME = field.NewString(tableName, "SECTOR_EN_NAME")
	_hCV_VIEW_SECTOR_USING_COUNT.SECTORNO = field.NewInt64(tableName, "SECTORNO")
	_hCV_VIEW_SECTOR_USING_COUNT.BOOKINGYN = field.NewString(tableName, "BOOKING_YN")
	_hCV_VIEW_SECTOR_USING_COUNT.MOBILEBOOKINGYN = field.NewString(tableName, "MOBILE_BOOKING_YN")
	_hCV_VIEW_SECTOR_USING_COUNT.ASSIGNYN = field.NewString(tableName, "ASSIGN_YN")
	_hCV_VIEW_SECTOR_USING_COUNT.MOBILEASSIGNYN = field.NewString(tableName, "MOBILE_ASSIGN_YN")
	_hCV_VIEW_SECTOR_USING_COUNT.TOTALCNT = field.NewInt64(tableName, "TOTAL_CNT")
	_hCV_VIEW_SECTOR_USING_COUNT.USECNT = field.NewInt64(tableName, "USE_CNT")
	_hCV_VIEW_SECTOR_USING_COUNT.LIBNO = field.NewInt64(tableName, "LIBNO")
	_hCV_VIEW_SECTOR_USING_COUNT.FLOORNO = field.NewInt64(tableName, "FLOORNO")
	_hCV_VIEW_SECTOR_USING_COUNT.ROOMNO = field.NewInt64(tableName, "ROOMNO")
	_hCV_VIEW_SECTOR_USING_COUNT.TYPENO = field.NewInt64(tableName, "TYPENO")
	_hCV_VIEW_SECTOR_USING_COUNT.FLOOR = field.NewInt64(tableName, "FLOOR")

	_hCV_VIEW_SECTOR_USING_COUNT.fillFieldMap()

	return _hCV_VIEW_SECTOR_USING_COUNT
}

type hCV_VIEW_SECTOR_USING_COUNT struct {
	hCV_VIEW_SECTOR_USING_COUNTDo

	ALL             field.Asterisk
	LIBNAME         field.String
	LIBENNAME       field.String
	FLOORNAME       field.String
	FLOORENNAME     field.String
	ROOMNAME        field.String
	ROOMENNAME      field.String
	SECTORNAME      field.String
	SECTORENNAME    field.String
	SECTORNO        field.Int64
	BOOKINGYN       field.String
	MOBILEBOOKINGYN field.String
	ASSIGNYN        field.String
	MOBILEASSIGNYN  field.String
	TOTALCNT        field.Int64
	USECNT          field.Int64
	LIBNO           field.Int64
	FLOORNO         field.Int64
	ROOMNO          field.Int64
	TYPENO          field.Int64
	FLOOR           field.Int64

	fieldMap map[string]field.Expr
}

func (h hCV_VIEW_SECTOR_USING_COUNT) Table(newTableName string) *hCV_VIEW_SECTOR_USING_COUNT {
	h.hCV_VIEW_SECTOR_USING_COUNTDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hCV_VIEW_SECTOR_USING_COUNT) As(alias string) *hCV_VIEW_SECTOR_USING_COUNT {
	h.hCV_VIEW_SECTOR_USING_COUNTDo.DO = *(h.hCV_VIEW_SECTOR_USING_COUNTDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hCV_VIEW_SECTOR_USING_COUNT) updateTableName(table string) *hCV_VIEW_SECTOR_USING_COUNT {
	h.ALL = field.NewAsterisk(table)
	h.LIBNAME = field.NewString(table, "LIB_NAME")
	h.LIBENNAME = field.NewString(table, "LIB_EN_NAME")
	h.FLOORNAME = field.NewString(table, "FLOOR_NAME")
	h.FLOORENNAME = field.NewString(table, "FLOOR_EN_NAME")
	h.ROOMNAME = field.NewString(table, "ROOM_NAME")
	h.ROOMENNAME = field.NewString(table, "ROOM_EN_NAME")
	h.SECTORNAME = field.NewString(table, "SECTOR_NAME")
	h.SECTORENNAME = field.NewString(table, "SECTOR_EN_NAME")
	h.SECTORNO = field.NewInt64(table, "SECTORNO")
	h.BOOKINGYN = field.NewString(table, "BOOKING_YN")
	h.MOBILEBOOKINGYN = field.NewString(table, "MOBILE_BOOKING_YN")
	h.ASSIGNYN = field.NewString(table, "ASSIGN_YN")
	h.MOBILEASSIGNYN = field.NewString(table, "MOBILE_ASSIGN_YN")
	h.TOTALCNT = field.NewInt64(table, "TOTAL_CNT")
	h.USECNT = field.NewInt64(table, "USE_CNT")
	h.LIBNO = field.NewInt64(table, "LIBNO")
	h.FLOORNO = field.NewInt64(table, "FLOORNO")
	h.ROOMNO = field.NewInt64(table, "ROOMNO")
	h.TYPENO = field.NewInt64(table, "TYPENO")
	h.FLOOR = field.NewInt64(table, "FLOOR")

	h.fillFieldMap()

	return h
}

func (h *hCV_VIEW_SECTOR_USING_COUNT) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hCV_VIEW_SECTOR_USING_COUNT) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 20)
	h.fieldMap["LIB_NAME"] = h.LIBNAME
	h.fieldMap["LIB_EN_NAME"] = h.LIBENNAME
	h.fieldMap["FLOOR_NAME"] = h.FLOORNAME
	h.fieldMap["FLOOR_EN_NAME"] = h.FLOORENNAME
	h.fieldMap["ROOM_NAME"] = h.ROOMNAME
	h.fieldMap["ROOM_EN_NAME"] = h.ROOMENNAME
	h.fieldMap["SECTOR_NAME"] = h.SECTORNAME
	h.fieldMap["SECTOR_EN_NAME"] = h.SECTORENNAME
	h.fieldMap["SECTORNO"] = h.SECTORNO
	h.fieldMap["BOOKING_YN"] = h.BOOKINGYN
	h.fieldMap["MOBILE_BOOKING_YN"] = h.MOBILEBOOKINGYN
	h.fieldMap["ASSIGN_YN"] = h.ASSIGNYN
	h.fieldMap["MOBILE_ASSIGN_YN"] = h.MOBILEASSIGNYN
	h.fieldMap["TOTAL_CNT"] = h.TOTALCNT
	h.fieldMap["USE_CNT"] = h.USECNT
	h.fieldMap["LIBNO"] = h.LIBNO
	h.fieldMap["FLOORNO"] = h.FLOORNO
	h.fieldMap["ROOMNO"] = h.ROOMNO
	h.fieldMap["TYPENO"] = h.TYPENO
	h.fieldMap["FLOOR"] = h.FLOOR
}

func (h hCV_VIEW_SECTOR_USING_COUNT) clone(db *gorm.DB) hCV_VIEW_SECTOR_USING_COUNT {
	h.hCV_VIEW_SECTOR_USING_COUNTDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hCV_VIEW_SECTOR_USING_COUNT) replaceDB(db *gorm.DB) hCV_VIEW_SECTOR_USING_COUNT {
	h.hCV_VIEW_SECTOR_USING_COUNTDo.ReplaceDB(db)
	return h
}

type hCV_VIEW_SECTOR_USING_COUNTDo struct{ gen.DO }

type IHCV_VIEW_SECTOR_USING_COUNTDo interface {
	gen.SubQuery
	Debug() IHCV_VIEW_SECTOR_USING_COUNTDo
	WithContext(ctx context.Context) IHCV_VIEW_SECTOR_USING_COUNTDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHCV_VIEW_SECTOR_USING_COUNTDo
	WriteDB() IHCV_VIEW_SECTOR_USING_COUNTDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHCV_VIEW_SECTOR_USING_COUNTDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHCV_VIEW_SECTOR_USING_COUNTDo
	Not(conds ...gen.Condition) IHCV_VIEW_SECTOR_USING_COUNTDo
	Or(conds ...gen.Condition) IHCV_VIEW_SECTOR_USING_COUNTDo
	Select(conds ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo
	Where(conds ...gen.Condition) IHCV_VIEW_SECTOR_USING_COUNTDo
	Order(conds ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo
	Distinct(cols ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo
	Omit(cols ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo
	Join(table schema.Tabler, on ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo
	Group(cols ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo
	Having(conds ...gen.Condition) IHCV_VIEW_SECTOR_USING_COUNTDo
	Limit(limit int) IHCV_VIEW_SECTOR_USING_COUNTDo
	Offset(offset int) IHCV_VIEW_SECTOR_USING_COUNTDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_VIEW_SECTOR_USING_COUNTDo
	Unscoped() IHCV_VIEW_SECTOR_USING_COUNTDo
	Create(values ...*model.HCV_VIEW_SECTOR_USING_COUNT) error
	CreateInBatches(values []*model.HCV_VIEW_SECTOR_USING_COUNT, batchSize int) error
	Save(values ...*model.HCV_VIEW_SECTOR_USING_COUNT) error
	First() (*model.HCV_VIEW_SECTOR_USING_COUNT, error)
	Take() (*model.HCV_VIEW_SECTOR_USING_COUNT, error)
	Last() (*model.HCV_VIEW_SECTOR_USING_COUNT, error)
	Find() ([]*model.HCV_VIEW_SECTOR_USING_COUNT, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_VIEW_SECTOR_USING_COUNT, err error)
	FindInBatches(result *[]*model.HCV_VIEW_SECTOR_USING_COUNT, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HCV_VIEW_SECTOR_USING_COUNT) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHCV_VIEW_SECTOR_USING_COUNTDo
	Assign(attrs ...field.AssignExpr) IHCV_VIEW_SECTOR_USING_COUNTDo
	Joins(fields ...field.RelationField) IHCV_VIEW_SECTOR_USING_COUNTDo
	Preload(fields ...field.RelationField) IHCV_VIEW_SECTOR_USING_COUNTDo
	FirstOrInit() (*model.HCV_VIEW_SECTOR_USING_COUNT, error)
	FirstOrCreate() (*model.HCV_VIEW_SECTOR_USING_COUNT, error)
	FindByPage(offset int, limit int) (result []*model.HCV_VIEW_SECTOR_USING_COUNT, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHCV_VIEW_SECTOR_USING_COUNTDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Debug() IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Debug())
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) WithContext(ctx context.Context) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) ReadDB() IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.Clauses(dbresolver.Read)
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) WriteDB() IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.Clauses(dbresolver.Write)
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Session(config *gorm.Session) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Session(config))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Clauses(conds ...clause.Expression) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Returning(value interface{}, columns ...string) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Not(conds ...gen.Condition) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Or(conds ...gen.Condition) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Select(conds ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Where(conds ...gen.Condition) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Order(conds ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Distinct(cols ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Omit(cols ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Join(table schema.Tabler, on ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) RightJoin(table schema.Tabler, on ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Group(cols ...field.Expr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Having(conds ...gen.Condition) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Limit(limit int) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Offset(offset int) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Unscoped() IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Create(values ...*model.HCV_VIEW_SECTOR_USING_COUNT) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) CreateInBatches(values []*model.HCV_VIEW_SECTOR_USING_COUNT, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hCV_VIEW_SECTOR_USING_COUNTDo) Save(values ...*model.HCV_VIEW_SECTOR_USING_COUNT) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) First() (*model.HCV_VIEW_SECTOR_USING_COUNT, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_SECTOR_USING_COUNT), nil
	}
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Take() (*model.HCV_VIEW_SECTOR_USING_COUNT, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_SECTOR_USING_COUNT), nil
	}
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Last() (*model.HCV_VIEW_SECTOR_USING_COUNT, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_SECTOR_USING_COUNT), nil
	}
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Find() ([]*model.HCV_VIEW_SECTOR_USING_COUNT, error) {
	result, err := h.DO.Find()
	return result.([]*model.HCV_VIEW_SECTOR_USING_COUNT), err
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_VIEW_SECTOR_USING_COUNT, err error) {
	buf := make([]*model.HCV_VIEW_SECTOR_USING_COUNT, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) FindInBatches(result *[]*model.HCV_VIEW_SECTOR_USING_COUNT, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Attrs(attrs ...field.AssignExpr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Assign(attrs ...field.AssignExpr) IHCV_VIEW_SECTOR_USING_COUNTDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Joins(fields ...field.RelationField) IHCV_VIEW_SECTOR_USING_COUNTDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Preload(fields ...field.RelationField) IHCV_VIEW_SECTOR_USING_COUNTDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) FirstOrInit() (*model.HCV_VIEW_SECTOR_USING_COUNT, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_SECTOR_USING_COUNT), nil
	}
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) FirstOrCreate() (*model.HCV_VIEW_SECTOR_USING_COUNT, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_SECTOR_USING_COUNT), nil
	}
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) FindByPage(offset int, limit int) (result []*model.HCV_VIEW_SECTOR_USING_COUNT, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hCV_VIEW_SECTOR_USING_COUNTDo) Delete(models ...*model.HCV_VIEW_SECTOR_USING_COUNT) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hCV_VIEW_SECTOR_USING_COUNTDo) withDO(do gen.Dao) *hCV_VIEW_SECTOR_USING_COUNTDo {
	h.DO = *do.(*gen.DO)
	return h
}
