// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"WISE_SOFTWARE/DB/model"
)

func newHCV_VIEW_GATE_HISTORY(db *gorm.DB, opts ...gen.DOOption) hCV_VIEW_GATE_HISTORY {
	_hCV_VIEW_GATE_HISTORY := hCV_VIEW_GATE_HISTORY{}

	_hCV_VIEW_GATE_HISTORY.hCV_VIEW_GATE_HISTORYDo.UseDB(db, opts...)
	_hCV_VIEW_GATE_HISTORY.hCV_VIEW_GATE_HISTORYDo.UseModel(&model.HCV_VIEW_GATE_HISTORY{})

	tableName := _hCV_VIEW_GATE_HISTORY.hCV_VIEW_GATE_HISTORYDo.TableName()
	_hCV_VIEW_GATE_HISTORY.ALL = field.NewAsterisk(tableName)
	_hCV_VIEW_GATE_HISTORY.SEQNO = field.NewInt64(tableName, "SEQNO")
	_hCV_VIEW_GATE_HISTORY.SCHOOLNO = field.NewString(tableName, "SCHOOLNO")
	_hCV_VIEW_GATE_HISTORY.GATE = field.NewInt64(tableName, "GATE")
	_hCV_VIEW_GATE_HISTORY.GATENO = field.NewString(tableName, "GATENO")
	_hCV_VIEW_GATE_HISTORY.GUBUN = field.NewString(tableName, "GUBUN")
	_hCV_VIEW_GATE_HISTORY.LOGTIME = field.NewTime(tableName, "LOGTIME")
	_hCV_VIEW_GATE_HISTORY.NAME = field.NewString(tableName, "NAME")
	_hCV_VIEW_GATE_HISTORY.SEX = field.NewString(tableName, "SEX")
	_hCV_VIEW_GATE_HISTORY.SOSOKCD1 = field.NewString(tableName, "SOSOK_CD1")
	_hCV_VIEW_GATE_HISTORY.SOSOKCD2 = field.NewString(tableName, "SOSOK_CD2")
	_hCV_VIEW_GATE_HISTORY.SINBUN = field.NewString(tableName, "SINBUN")
	_hCV_VIEW_GATE_HISTORY.STATUSCD = field.NewString(tableName, "STATUS_CD")

	_hCV_VIEW_GATE_HISTORY.fillFieldMap()

	return _hCV_VIEW_GATE_HISTORY
}

type hCV_VIEW_GATE_HISTORY struct {
	hCV_VIEW_GATE_HISTORYDo

	ALL      field.Asterisk
	SEQNO    field.Int64
	SCHOOLNO field.String
	GATE     field.Int64
	GATENO   field.String
	GUBUN    field.String
	LOGTIME  field.Time
	NAME     field.String
	SEX      field.String
	SOSOKCD1 field.String
	SOSOKCD2 field.String
	SINBUN   field.String
	STATUSCD field.String

	fieldMap map[string]field.Expr
}

func (h hCV_VIEW_GATE_HISTORY) Table(newTableName string) *hCV_VIEW_GATE_HISTORY {
	h.hCV_VIEW_GATE_HISTORYDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hCV_VIEW_GATE_HISTORY) As(alias string) *hCV_VIEW_GATE_HISTORY {
	h.hCV_VIEW_GATE_HISTORYDo.DO = *(h.hCV_VIEW_GATE_HISTORYDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hCV_VIEW_GATE_HISTORY) updateTableName(table string) *hCV_VIEW_GATE_HISTORY {
	h.ALL = field.NewAsterisk(table)
	h.SEQNO = field.NewInt64(table, "SEQNO")
	h.SCHOOLNO = field.NewString(table, "SCHOOLNO")
	h.GATE = field.NewInt64(table, "GATE")
	h.GATENO = field.NewString(table, "GATENO")
	h.GUBUN = field.NewString(table, "GUBUN")
	h.LOGTIME = field.NewTime(table, "LOGTIME")
	h.NAME = field.NewString(table, "NAME")
	h.SEX = field.NewString(table, "SEX")
	h.SOSOKCD1 = field.NewString(table, "SOSOK_CD1")
	h.SOSOKCD2 = field.NewString(table, "SOSOK_CD2")
	h.SINBUN = field.NewString(table, "SINBUN")
	h.STATUSCD = field.NewString(table, "STATUS_CD")

	h.fillFieldMap()

	return h
}

func (h *hCV_VIEW_GATE_HISTORY) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hCV_VIEW_GATE_HISTORY) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 12)
	h.fieldMap["SEQNO"] = h.SEQNO
	h.fieldMap["SCHOOLNO"] = h.SCHOOLNO
	h.fieldMap["GATE"] = h.GATE
	h.fieldMap["GATENO"] = h.GATENO
	h.fieldMap["GUBUN"] = h.GUBUN
	h.fieldMap["LOGTIME"] = h.LOGTIME
	h.fieldMap["NAME"] = h.NAME
	h.fieldMap["SEX"] = h.SEX
	h.fieldMap["SOSOK_CD1"] = h.SOSOKCD1
	h.fieldMap["SOSOK_CD2"] = h.SOSOKCD2
	h.fieldMap["SINBUN"] = h.SINBUN
	h.fieldMap["STATUS_CD"] = h.STATUSCD
}

func (h hCV_VIEW_GATE_HISTORY) clone(db *gorm.DB) hCV_VIEW_GATE_HISTORY {
	h.hCV_VIEW_GATE_HISTORYDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hCV_VIEW_GATE_HISTORY) replaceDB(db *gorm.DB) hCV_VIEW_GATE_HISTORY {
	h.hCV_VIEW_GATE_HISTORYDo.ReplaceDB(db)
	return h
}

type hCV_VIEW_GATE_HISTORYDo struct{ gen.DO }

type IHCV_VIEW_GATE_HISTORYDo interface {
	gen.SubQuery
	Debug() IHCV_VIEW_GATE_HISTORYDo
	WithContext(ctx context.Context) IHCV_VIEW_GATE_HISTORYDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHCV_VIEW_GATE_HISTORYDo
	WriteDB() IHCV_VIEW_GATE_HISTORYDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHCV_VIEW_GATE_HISTORYDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHCV_VIEW_GATE_HISTORYDo
	Not(conds ...gen.Condition) IHCV_VIEW_GATE_HISTORYDo
	Or(conds ...gen.Condition) IHCV_VIEW_GATE_HISTORYDo
	Select(conds ...field.Expr) IHCV_VIEW_GATE_HISTORYDo
	Where(conds ...gen.Condition) IHCV_VIEW_GATE_HISTORYDo
	Order(conds ...field.Expr) IHCV_VIEW_GATE_HISTORYDo
	Distinct(cols ...field.Expr) IHCV_VIEW_GATE_HISTORYDo
	Omit(cols ...field.Expr) IHCV_VIEW_GATE_HISTORYDo
	Join(table schema.Tabler, on ...field.Expr) IHCV_VIEW_GATE_HISTORYDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_VIEW_GATE_HISTORYDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHCV_VIEW_GATE_HISTORYDo
	Group(cols ...field.Expr) IHCV_VIEW_GATE_HISTORYDo
	Having(conds ...gen.Condition) IHCV_VIEW_GATE_HISTORYDo
	Limit(limit int) IHCV_VIEW_GATE_HISTORYDo
	Offset(offset int) IHCV_VIEW_GATE_HISTORYDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_VIEW_GATE_HISTORYDo
	Unscoped() IHCV_VIEW_GATE_HISTORYDo
	Create(values ...*model.HCV_VIEW_GATE_HISTORY) error
	CreateInBatches(values []*model.HCV_VIEW_GATE_HISTORY, batchSize int) error
	Save(values ...*model.HCV_VIEW_GATE_HISTORY) error
	First() (*model.HCV_VIEW_GATE_HISTORY, error)
	Take() (*model.HCV_VIEW_GATE_HISTORY, error)
	Last() (*model.HCV_VIEW_GATE_HISTORY, error)
	Find() ([]*model.HCV_VIEW_GATE_HISTORY, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_VIEW_GATE_HISTORY, err error)
	FindInBatches(result *[]*model.HCV_VIEW_GATE_HISTORY, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HCV_VIEW_GATE_HISTORY) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHCV_VIEW_GATE_HISTORYDo
	Assign(attrs ...field.AssignExpr) IHCV_VIEW_GATE_HISTORYDo
	Joins(fields ...field.RelationField) IHCV_VIEW_GATE_HISTORYDo
	Preload(fields ...field.RelationField) IHCV_VIEW_GATE_HISTORYDo
	FirstOrInit() (*model.HCV_VIEW_GATE_HISTORY, error)
	FirstOrCreate() (*model.HCV_VIEW_GATE_HISTORY, error)
	FindByPage(offset int, limit int) (result []*model.HCV_VIEW_GATE_HISTORY, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHCV_VIEW_GATE_HISTORYDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hCV_VIEW_GATE_HISTORYDo) Debug() IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Debug())
}

func (h hCV_VIEW_GATE_HISTORYDo) WithContext(ctx context.Context) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hCV_VIEW_GATE_HISTORYDo) ReadDB() IHCV_VIEW_GATE_HISTORYDo {
	return h.Clauses(dbresolver.Read)
}

func (h hCV_VIEW_GATE_HISTORYDo) WriteDB() IHCV_VIEW_GATE_HISTORYDo {
	return h.Clauses(dbresolver.Write)
}

func (h hCV_VIEW_GATE_HISTORYDo) Session(config *gorm.Session) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Session(config))
}

func (h hCV_VIEW_GATE_HISTORYDo) Clauses(conds ...clause.Expression) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Returning(value interface{}, columns ...string) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Not(conds ...gen.Condition) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Or(conds ...gen.Condition) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Select(conds ...field.Expr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Where(conds ...gen.Condition) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Order(conds ...field.Expr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Distinct(cols ...field.Expr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Omit(cols ...field.Expr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Join(table schema.Tabler, on ...field.Expr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hCV_VIEW_GATE_HISTORYDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hCV_VIEW_GATE_HISTORYDo) RightJoin(table schema.Tabler, on ...field.Expr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Group(cols ...field.Expr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Having(conds ...gen.Condition) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Limit(limit int) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hCV_VIEW_GATE_HISTORYDo) Offset(offset int) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hCV_VIEW_GATE_HISTORYDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Unscoped() IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hCV_VIEW_GATE_HISTORYDo) Create(values ...*model.HCV_VIEW_GATE_HISTORY) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hCV_VIEW_GATE_HISTORYDo) CreateInBatches(values []*model.HCV_VIEW_GATE_HISTORY, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hCV_VIEW_GATE_HISTORYDo) Save(values ...*model.HCV_VIEW_GATE_HISTORY) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hCV_VIEW_GATE_HISTORYDo) First() (*model.HCV_VIEW_GATE_HISTORY, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_GATE_HISTORY), nil
	}
}

func (h hCV_VIEW_GATE_HISTORYDo) Take() (*model.HCV_VIEW_GATE_HISTORY, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_GATE_HISTORY), nil
	}
}

func (h hCV_VIEW_GATE_HISTORYDo) Last() (*model.HCV_VIEW_GATE_HISTORY, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_GATE_HISTORY), nil
	}
}

func (h hCV_VIEW_GATE_HISTORYDo) Find() ([]*model.HCV_VIEW_GATE_HISTORY, error) {
	result, err := h.DO.Find()
	return result.([]*model.HCV_VIEW_GATE_HISTORY), err
}

func (h hCV_VIEW_GATE_HISTORYDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HCV_VIEW_GATE_HISTORY, err error) {
	buf := make([]*model.HCV_VIEW_GATE_HISTORY, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hCV_VIEW_GATE_HISTORYDo) FindInBatches(result *[]*model.HCV_VIEW_GATE_HISTORY, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hCV_VIEW_GATE_HISTORYDo) Attrs(attrs ...field.AssignExpr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Assign(attrs ...field.AssignExpr) IHCV_VIEW_GATE_HISTORYDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hCV_VIEW_GATE_HISTORYDo) Joins(fields ...field.RelationField) IHCV_VIEW_GATE_HISTORYDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hCV_VIEW_GATE_HISTORYDo) Preload(fields ...field.RelationField) IHCV_VIEW_GATE_HISTORYDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hCV_VIEW_GATE_HISTORYDo) FirstOrInit() (*model.HCV_VIEW_GATE_HISTORY, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_GATE_HISTORY), nil
	}
}

func (h hCV_VIEW_GATE_HISTORYDo) FirstOrCreate() (*model.HCV_VIEW_GATE_HISTORY, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HCV_VIEW_GATE_HISTORY), nil
	}
}

func (h hCV_VIEW_GATE_HISTORYDo) FindByPage(offset int, limit int) (result []*model.HCV_VIEW_GATE_HISTORY, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hCV_VIEW_GATE_HISTORYDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hCV_VIEW_GATE_HISTORYDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hCV_VIEW_GATE_HISTORYDo) Delete(models ...*model.HCV_VIEW_GATE_HISTORY) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hCV_VIEW_GATE_HISTORYDo) withDO(do gen.Dao) *hCV_VIEW_GATE_HISTORYDo {
	h.DO = *do.(*gen.DO)
	return h
}
