// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAPPLYROOM = "APPLY_ROOM"

// APPLYROOM mapped from table <APPLY_ROOM>
type APPLYROOM struct {
	KIOSKNO    string  `gorm:"column:KIOSK_NO;not null" json:"KIOSK_NO"`
	ROOMNAME   string  `gorm:"column:ROOM_NAME;not null" json:"ROOM_NAME"`
	SEATNOS    string  `gorm:"column:SEAT_NO_S;not null" json:"SEAT_NO_S"`
	SEATNOE    string  `gorm:"column:SEAT_NO_E;not null" json:"SEAT_NO_E"`
	SEATNOCNT  string  `gorm:"column:SEAT_NO_CNT;not null" json:"SEAT_NO_CNT"`
	SEATFIX    *string `gorm:"column:SEAT_FIX" json:"SEAT_FIX"`
	USEYN      *string `gorm:"column:USE_YN;not null;default:Y" json:"USE_YN"`
	INSERTDATE string  `gorm:"column:INSERT_DATE;not null" json:"INSERT_DATE"`
	UPDATEDATE *string `gorm:"column:UPDATE_DATE" json:"UPDATE_DATE"`
	BIGO       *string `gorm:"column:BIGO" json:"BIGO"`
}

// TableName APPLYROOM's table name
func (*APPLYROOM) TableName() string {
	return TableNameAPPLYROOM
}
