// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBLACKLIST2LOG = "BLACKLIST2_LOG"

// BLACKLIST2LOG mapped from table <BLACKLIST2_LOG>
type BLACKLIST2LOG struct {
	ID         int64      `gorm:"column:ID;not null" json:"ID"`
	BSEQNO     *int64     `gorm:"column:BSEQNO" json:"BSEQNO"`
	STATUS     *int64     `gorm:"column:STATUS" json:"STATUS"`
	SCHOOLNO   *string    `gorm:"column:SCHOOLNO" json:"SCHOOLNO"`
	RETURNTIME *time.Time `gorm:"column:RETURNTIME" json:"RETURNTIME"`
	MISSCNT    *int64     `gorm:"column:MISS_CNT" json:"MISS_CNT"`
}

// TableName BLACKLIST2LOG's table name
func (*BLACKLIST2LOG) TableName() string {
	return TableNameBLACKLIST2LOG
}
