// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHoliday = "holiday"

// Holiday mapped from table <holiday>
type Holiday struct {
	Holiday string `gorm:"column:holiday;not null" json:"holiday"`
	Bigo    string `gorm:"column:bigo;not null" json:"bigo"`
}

// TableName Holiday's table name
func (*Holiday) TableName() string {
	return TableNameHoliday
}
