// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMOBILEBTNOPT = "MOBILE_BTN_OPT"

// MOBILEBTNOPT mapped from table <MOBILE_BTN_OPT>
type MOBILEBTNOPT struct {
	ID           int64  `gorm:"column:ID;primaryKey" json:"ID"`
	SEATASSIGN   *int64 `gorm:"column:SEAT_ASSIGN" json:"SEAT_ASSIGN"`
	SEATBOOKING  *int64 `gorm:"column:SEAT_BOOKING" json:"SEAT_BOOKING"`
	GROUPBOOKING *int64 `gorm:"column:GROUP_BOOKING" json:"GROUP_BOOKING"`
	BOOKINGCHECK *int64 `gorm:"column:BOOKING_CHECK" json:"BOOKING_CHECK"`
	ALARM        *int64 `gorm:"column:ALARM" json:"ALARM"`
	NFC          *int64 `gorm:"column:NFC" json:"NFC"`
	QR           *int64 `gorm:"column:QR" json:"QR"`
}

// TableName MOBILEBTNOPT's table name
func (*MOBILEBTNOPT) TableName() string {
	return TableNameMOBILEBTNOPT
}
