// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePATMAST = "PATMAST"

// PATMAST mapped from table <PATMAST>
type PATMAST struct {
	AltPid      *string `gorm:"column:alt_pid" json:"alt_pid"`
	RpstPersNo  *string `gorm:"column:rpst_pers_no" json:"rpst_pers_no"`
	Username    *string `gorm:"column:username" json:"username"`
	PatType     *string `gorm:"column:pat_type" json:"pat_type"`
	PatName     *string `gorm:"column:pat_name" json:"pat_name"`
	DeptCode    *string `gorm:"column:dept_code" json:"dept_code"`
	DeptName    *string `gorm:"column:dept_name" json:"dept_name"`
	CollegeCode *string `gorm:"column:college_code" json:"college_code"`
	CollegeName *string `gorm:"column:college_name" json:"college_name"`
	Phone3      *string `gorm:"column:phone3" json:"phone3"`
	Email       *string `gorm:"column:email" json:"email"`
	DateExprd   *string `gorm:"column:date_exprd" json:"date_exprd"`
	PatStat     *string `gorm:"column:pat_stat" json:"pat_stat"`
	Ipid        *int64  `gorm:"column:ipid" json:"ipid"`
	Userpwd     *string `gorm:"column:userpwd" json:"userpwd"`
}

// TableName PATMAST's table name
func (*PATMAST) TableName() string {
	return TableNamePATMAST
}
