// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeatWorkdaytype = "seat_workdaytype"

// SeatWorkdaytype mapped from table <seat_workdaytype>
type SeatWorkdaytype struct {
	YMD        int64   `gorm:"column:YMD;primaryKey" json:"YMD"`
	WEEK       int64   `gorm:"column:WEEK;primaryKey" json:"WEEK"`
	TITLE      *string `gorm:"column:TITLE" json:"TITLE"`
	ENTITLE    *string `gorm:"column:EN_TITLE" json:"EN_TITLE"`
	NORMAL     *int64  `gorm:"column:NORMAL" json:"NORMAL"`
	VACATION   *int64  `gorm:"column:VACATION" json:"VACATION"`
	TITLEMSG   *string `gorm:"column:TITLE_MSG" json:"TITLE_MSG"`
	ENTITLEMSG *string `gorm:"column:EN_TITLE_MSG" json:"EN_TITLE_MSG"`
}

// TableName SeatWorkdaytype's table name
func (*SeatWorkdaytype) TableName() string {
	return TableNameSeatWorkdaytype
}
