// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeatUse = "seat_use"

// SeatUse mapped from table <seat_use>
type SeatUse struct {
	KioskNo     *int64  `gorm:"column:kiosk_no" json:"kiosk_no"`
	RoomNo      *int64  `gorm:"column:room_no" json:"room_no"`
	SeatNo      *int64  `gorm:"column:seat_no" json:"seat_no"`
	UserID      *string `gorm:"column:user_id" json:"user_id"`
	StartTime   *string `gorm:"column:start_time" json:"start_time"`
	EndTime     *string `gorm:"column:end_time" json:"end_time"`
	ContCnt     *int64  `gorm:"column:cont_cnt" json:"cont_cnt"`
	PatType     *string `gorm:"column:pat_type" json:"pat_type"`
	DeptCode    *string `gorm:"column:dept_code" json:"dept_code"`
	SeatBigo    *string `gorm:"column:seat_bigo" json:"seat_bigo"`
	ManGubun    *string `gorm:"column:man_gubun" json:"man_gubun"`
	GateOutTime *string `gorm:"column:gate_out_time" json:"gate_out_time"`
	GateInTime  *string `gorm:"column:gate_in_time" json:"gate_in_time"`
	ReserveTime *string `gorm:"column:reserve_time" json:"reserve_time"`
}

// TableName SeatUse's table name
func (*SeatUse) TableName() string {
	return TableNameSeatUse
}
