// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeatRoomExam = "seat_room_exam"

// SeatRoomExam mapped from table <seat_room_exam>
type SeatRoomExam struct {
	ExamGubun      *string `gorm:"column:exam_gubun" json:"exam_gubun"`
	RoomNo         *int64  `gorm:"column:room_no" json:"room_no"`
	RoomName       *string `gorm:"column:room_name" json:"room_name"`
	SeatNoS        *int64  `gorm:"column:seat_no_s" json:"seat_no_s"`
	SeatNoE        *int64  `gorm:"column:seat_no_e" json:"seat_no_e"`
	SeatNoCnt      *int64  `gorm:"column:seat_no_cnt" json:"seat_no_cnt"`
	ColorUse       *int64  `gorm:"column:color_use" json:"color_use"`
	ColorNuse      *int64  `gorm:"column:color_nuse" json:"color_nuse"`
	TimeStart      *string `gorm:"column:time_start" json:"time_start"`
	TimeEnd        *string `gorm:"column:time_end" json:"time_end"`
	UseHour        *int64  `gorm:"column:use_hour" json:"use_hour"`
	ContMin        *int64  `gorm:"column:cont_min" json:"cont_min"`
	ContCnt        *int64  `gorm:"column:cont_cnt" json:"cont_cnt"`
	SeatFix        *string `gorm:"column:seat_fix" json:"seat_fix"`
	LimitPat       *string `gorm:"column:limit_pat" json:"limit_pat"`
	LimitPatGu     *string `gorm:"column:limit_pat_gu" json:"limit_pat_gu"`
	LimitDept      *string `gorm:"column:limit_dept" json:"limit_dept"`
	LimitDeptGu    *string `gorm:"column:limit_dept_gu" json:"limit_dept_gu"`
	LimitStat      *string `gorm:"column:limit_stat" json:"limit_stat"`
	LimitStatGu    *string `gorm:"column:limit_stat_gu" json:"limit_stat_gu"`
	RoomBigo       *string `gorm:"column:room_bigo" json:"room_bigo"`
	ColorUsem      *int64  `gorm:"column:color_usem" json:"color_usem"`
	ColorUsef      *int64  `gorm:"column:color_usef" json:"color_usef"`
	LimitYearS     *int64  `gorm:"column:limit_year_s" json:"limit_year_s"`
	LimitYearE     *int64  `gorm:"column:limit_year_e" json:"limit_year_e"`
	LimitSeatpat   *string `gorm:"column:limit_seatpat" json:"limit_seatpat"`
	LimitSeatpatGu *int64  `gorm:"column:limit_seatpat_gu" json:"limit_seatpat_gu"`
	LimitPatcnt    *string `gorm:"column:limit_patcnt" json:"limit_patcnt"`
	LimitPatcntGu  *int64  `gorm:"column:limit_patcnt_gu" json:"limit_patcnt_gu"`
	LimitGenderm   *string `gorm:"column:limit_genderm" json:"limit_genderm"`
	LimitGendermGu *int64  `gorm:"column:limit_genderm_gu" json:"limit_genderm_gu"`
	LimitGenderf   *string `gorm:"column:limit_genderf" json:"limit_genderf"`
	LimitGenderfGu *int64  `gorm:"column:limit_genderf_gu" json:"limit_genderf_gu"`
}

// TableName SeatRoomExam's table name
func (*SeatRoomExam) TableName() string {
	return TableNameSeatRoomExam
}
