// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSeatTmp = "seat_tmp"

// SeatTmp mapped from table <seat_tmp>
type SeatTmp struct {
	Bseqno    int64      `gorm:"column:bseqno;primaryKey" json:"bseqno"`
	Starttime *time.Time `gorm:"column:starttime" json:"starttime"`
	Test      *string    `gorm:"column:test" json:"test"`
}

// TableName SeatTmp's table name
func (*SeatTmp) TableName() string {
	return TableNameSeatTmp
}
