// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeatStatLimit = "seat_stat_limit"

// SeatStatLimit mapped from table <seat_stat_limit>
type SeatStatLimit struct {
	StatCode *int64  `gorm:"column:stat_code" json:"stat_code"`
	StatName *string `gorm:"column:stat_name" json:"stat_name"`
	BlockDay *string `gorm:"column:block_day" json:"block_day"`
	BlockCnt *int64  `gorm:"column:block_cnt" json:"block_cnt"`
	UseYn    *string `gorm:"column:use_yn" json:"use_yn"`
	StatGb   *string `gorm:"column:stat_gb" json:"stat_gb"`
}

// TableName SeatStatLimit's table name
func (*SeatStatLimit) TableName() string {
	return TableNameSeatStatLimit
}
