// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeatConfBak = "seat_conf_bak"

// SeatConfBak mapped from table <seat_conf_bak>
type SeatConfBak struct {
	SeatCode  *string `gorm:"column:seat_code" json:"seat_code"`
	CodeValue *string `gorm:"column:code_value" json:"code_value"`
}

// TableName SeatConfBak's table name
func (*SeatConfBak) TableName() string {
	return TableNameSeatConfBak
}
