// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSeatBookingLog = "seat_booking_log"

// SeatBookingLog mapped from table <seat_booking_log>
type SeatBookingLog struct {
	LOGNO       int64      `gorm:"column:LOGNO;primaryKey" json:"LOGNO"`
	BSEQNO      *int64     `gorm:"column:BSEQNO" json:"BSEQNO"`
	SCHOOLNO    *string    `gorm:"column:SCHOOLNO" json:"SCHOOLNO"`
	SEATNO      *int64     `gorm:"column:SEATNO" json:"SEATNO"`
	STATUS      *int64     `gorm:"column:STATUS" json:"STATUS"`
	USESTART    *time.Time `gorm:"column:USESTART" json:"USESTART"`
	USEEXPIRE   *time.Time `gorm:"column:USEEXPIRE" json:"USEEXPIRE"`
	STARTTIME   *time.Time `gorm:"column:STARTTIME" json:"STARTTIME"`
	RETURNTIME  *time.Time `gorm:"column:RETURNTIME" json:"RETURNTIME"`
	NEWSEATNO   *int64     `gorm:"column:NEW_SEATNO" json:"NEW_SEATNO"`
	EXTENDMIN   *int64     `gorm:"column:EXTEND_MIN" json:"EXTEND_MIN"`
	EXTENDCNT   *int64     `gorm:"column:EXTEND_CNT" json:"EXTEND_CNT"`
	LOGTIME     *time.Time `gorm:"column:LOGTIME" json:"LOGTIME"`
	ISSUEFROM   *int64     `gorm:"column:ISSUEFROM" json:"ISSUEFROM"`
	ISSUEDETAIL *string    `gorm:"column:ISSUEDETAIL" json:"ISSUEDETAIL"`
	ISSUETYPENO *int64     `gorm:"column:ISSUE_TYPE_NO" json:"ISSUE_TYPE_NO"`
}

// TableName SeatBookingLog's table name
func (*SeatBookingLog) TableName() string {
	return TableNameSeatBookingLog
}
