// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeatSector = "seat_sector"

// SeatSector mapped from table <seat_sector>
type SeatSector struct {
	SECTORNO        int64   `gorm:"column:SECTORNO;primaryKey" json:"SECTORNO"`
	NAME            *string `gorm:"column:NAME" json:"NAME"`
	ENNAME          *string `gorm:"column:EN_NAME" json:"EN_NAME"`
	TYPENO          *int64  `gorm:"column:TYPENO" json:"TYPENO"`
	ROOMNO          *int64  `gorm:"column:ROOMNO" json:"ROOMNO"`
	FLOORNO         *int64  `gorm:"column:FLOORNO" json:"FLOORNO"`
	BOOKINGYN       *string `gorm:"column:BOOKING_YN" json:"BOOKING_YN"`
	ASSIGNYN        *string `gorm:"column:ASSIGN_YN" json:"ASSIGN_YN"`
	MOBILEBOOKINGYN *string `gorm:"column:MOBILE_BOOKING_YN" json:"MOBILE_BOOKING_YN"`
	MOBILEASSIGNYN  *string `gorm:"column:MOBILE_ASSIGN_YN" json:"MOBILE_ASSIGN_YN"`
	DAYFROM         *int64  `gorm:"column:DAY_FROM" json:"DAY_FROM"`
	DAYTO           *int64  `gorm:"column:DAY_TO" json:"DAY_TO"`
	USEAPPROVAL     *int64  `gorm:"column:USE_APPROVAL" json:"USE_APPROVAL"`
	MEDIABOOKINGYN  *string `gorm:"column:MEDIA_BOOKING_YN" json:"MEDIA_BOOKING_YN"`
	EQUIPBOOKINGYN  *string `gorm:"column:EQUIP_BOOKING_YN" json:"EQUIP_BOOKING_YN"`
	SECTORIMAGE     *string `gorm:"column:SECTOR_IMAGE" json:"SECTOR_IMAGE"`
	SECTORIMAGE2    *string `gorm:"column:SECTOR_IMAGE2" json:"SECTOR_IMAGE2"`
}

// TableName SeatSector's table name
func (*SeatSector) TableName() string {
	return TableNameSeatSector
}
