// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeatLib = "seat_lib"

// SeatLib mapped from table <seat_lib>
type SeatLib struct {
	LIBNO  int64   `gorm:"column:LIBNO;primaryKey" json:"LIBNO"`
	NAME   *string `gorm:"column:NAME" json:"NAME"`
	ENNAME *string `gorm:"column:EN_NAME" json:"EN_NAME"`
	SORT   *int64  `gorm:"column:SORT" json:"SORT"`
}

// TableName SeatLib's table name
func (*SeatLib) TableName() string {
	return TableNameSeatLib
}
