// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeatActlog = "seat_actlog"

// SeatActlog mapped from table <seat_actlog>
type SeatActlog struct {
	ActTime  *string `gorm:"column:act_time" json:"act_time"`
	UserID   *string `gorm:"column:user_id" json:"user_id"`
	ActGubun *int64  `gorm:"column:act_gubun" json:"act_gubun"`
	PatType  *string `gorm:"column:pat_type" json:"pat_type"`
	DeptCode *string `gorm:"column:dept_code" json:"dept_code"`
	KioskNo  *int64  `gorm:"column:kiosk_no" json:"kiosk_no"`
	TimeZone *string `gorm:"column:time_zone" json:"time_zone"`
}

// TableName SeatActlog's table name
func (*SeatActlog) TableName() string {
	return TableNameSeatActlog
}
