// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTempGrbooking = "temp_grbooking"

// TempGrbooking mapped from table <temp_grbooking>
type TempGrbooking struct {
	BSEQNO  int64   `gorm:"column:BSEQNO;not null" json:"BSEQNO"`
	MEMBERS *string `gorm:"column:MEMBERS" json:"MEMBERS"`
}

// TableName TempGrbooking's table name
func (*TempGrbooking) TableName() string {
	return TableNameTempGrbooking
}
