// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHCV_TV_LASTYEAR_MONTH_USE = "TV_LASTYEAR_MONTH_USE"

// HCV_TV_LASTYEAR_MONTH_USE mapped from table <TV_LASTYEAR_MONTH_USE>
type HCV_TV_LASTYEAR_MONTH_USE struct {
	Libno    int64   `gorm:"column:libno;not null" json:"libno"`
	UseMonth *string `gorm:"column:use_month" json:"use_month"`
	UseCnt   *int64  `gorm:"column:use_cnt" json:"use_cnt"`
}

// TableName HCV_TV_LASTYEAR_MONTH_USE's table name
func (*HCV_TV_LASTYEAR_MONTH_USE) TableName() string {
	return TableNameHCV_TV_LASTYEAR_MONTH_USE
}
