// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHCV_TV_YESTERDAY_USE_TIME2 = "TV_YESTERDAY_USE_TIME2"

// HCV_TV_YESTERDAY_USE_TIME2 mapped from table <TV_YESTERDAY_USE_TIME2>
type HCV_TV_YESTERDAY_USE_TIME2 struct {
	Libno   int64   `gorm:"column:libno;not null" json:"libno"`
	UseDate *string `gorm:"column:use_date" json:"use_date"`
	Status  *int64  `gorm:"column:status" json:"status"`
	Gubun   int64   `gorm:"column:gubun;not null" json:"gubun"`
	T00     int64   `gorm:"column:t00;not null" json:"t00"`
	T01     int64   `gorm:"column:t01;not null" json:"t01"`
	T02     int64   `gorm:"column:t02;not null" json:"t02"`
	T03     int64   `gorm:"column:t03;not null" json:"t03"`
	T04     int64   `gorm:"column:t04;not null" json:"t04"`
	T05     int64   `gorm:"column:t05;not null" json:"t05"`
	T06     int64   `gorm:"column:t06;not null" json:"t06"`
	T07     int64   `gorm:"column:t07;not null" json:"t07"`
	T08     int64   `gorm:"column:t08;not null" json:"t08"`
	T09     int64   `gorm:"column:t09;not null" json:"t09"`
	T10     int64   `gorm:"column:t10;not null" json:"t10"`
	T11     int64   `gorm:"column:t11;not null" json:"t11"`
	T12     int64   `gorm:"column:t12;not null" json:"t12"`
	T13     int64   `gorm:"column:t13;not null" json:"t13"`
	T14     int64   `gorm:"column:t14;not null" json:"t14"`
	T15     int64   `gorm:"column:t15;not null" json:"t15"`
	T16     int64   `gorm:"column:t16;not null" json:"t16"`
	T17     int64   `gorm:"column:t17;not null" json:"t17"`
	T18     int64   `gorm:"column:t18;not null" json:"t18"`
	T19     int64   `gorm:"column:t19;not null" json:"t19"`
	T20     int64   `gorm:"column:t20;not null" json:"t20"`
	T21     int64   `gorm:"column:t21;not null" json:"t21"`
	T22     int64   `gorm:"column:t22;not null" json:"t22"`
	T23     int64   `gorm:"column:t23;not null" json:"t23"`
}

// TableName HCV_TV_YESTERDAY_USE_TIME2's table name
func (*HCV_TV_YESTERDAY_USE_TIME2) TableName() string {
	return TableNameHCV_TV_YESTERDAY_USE_TIME2
}
