// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHCV_view_date_status = "view_date_status"

// HCV_view_date_status mapped from table <view_date_status>
type HCV_view_date_status struct {
	Regdate *string `gorm:"column:regdate" json:"regdate"`
	Status  *int64  `gorm:"column:status" json:"status"`
	Cnt     *int64  `gorm:"column:cnt" json:"cnt"`
}

// TableName HCV_view_date_status's table name
func (*HCV_view_date_status) TableName() string {
	return TableNameHCV_view_date_status
}
