// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHCV_VIEW_PUSHMSG_LOG = "VIEW_PUSHMSG_LOG"

// HCV_VIEW_PUSHMSG_LOG mapped from table <VIEW_PUSHMSG_LOG>
type HCV_VIEW_PUSHMSG_LOG struct {
	AltPid       *string    `gorm:"column:alt_pid" json:"alt_pid"`
	Username     *string    `gorm:"column:username" json:"username"`
	PatName      *string    `gorm:"column:pat_name" json:"pat_name"`
	DeptName     *string    `gorm:"column:dept_name" json:"dept_name"`
	CollegeName  *string    `gorm:"column:college_name" json:"college_name"`
	REGTIME      *time.Time `gorm:"column:REGTIME" json:"REGTIME"`
	REALSENDTIME *time.Time `gorm:"column:REALSENDTIME" json:"REALSENDTIME"`
	SMSTXT       *string    `gorm:"column:SMS_TXT" json:"SMS_TXT"`
	ISSUETYPE    *int64     `gorm:"column:ISSUE_TYPE" json:"ISSUE_TYPE"`
}

// TableName HCV_VIEW_PUSHMSG_LOG's table name
func (*HCV_VIEW_PUSHMSG_LOG) TableName() string {
	return TableNameHCV_VIEW_PUSHMSG_LOG
}
