// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHCV_vw_busTest = "vw_busTest"

// HCV_vw_busTest mapped from table <vw_busTest>
type HCV_vw_busTest struct {
	BusStopID  int64    `gorm:"column:busStopID;not null" json:"busStopID"`
	StopCoordX float64  `gorm:"column:stopCoordX;not null" json:"stopCoordX"`
	StopCoordY float64  `gorm:"column:stopCoordY;not null" json:"stopCoordY"`
	StopName   string   `gorm:"column:stopName;not null" json:"stopName"`
	Distance   *float64 `gorm:"column:distance" json:"distance"`
}

// TableName HCV_vw_busTest's table name
func (*HCV_vw_busTest) TableName() string {
	return TableNameHCV_vw_busTest
}
