// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWiseCarrelReserveSub = "wise_carrel_reserve_sub"

// WiseCarrelReserveSub mapped from table <wise_carrel_reserve_sub>
type WiseCarrelReserveSub struct {
	ReserveNo   string `gorm:"column:reserve_no;not null" json:"reserve_no"`
	ReserveDate string `gorm:"column:reserve_date;not null" json:"reserve_date"`
	ReserveStat string `gorm:"column:reserve_stat;not null" json:"reserve_stat"`
	CarrelNo    string `gorm:"column:carrel_no;not null" json:"carrel_no"`
	UserID      string `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName WiseCarrelReserveSub's table name
func (*WiseCarrelReserveSub) TableName() string {
	return TableNameWiseCarrelReserveSub
}
