// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWiseDroom = "wise_droom"

// WiseDroom mapped from table <wise_droom>
type WiseDroom struct {
	DroomNo    *int64  `gorm:"column:droom_no" json:"droom_no"`
	DroomName  *string `gorm:"column:droom_name" json:"droom_name"`
	DroomGubun *string `gorm:"column:droom_gubun" json:"droom_gubun"`
	SeatCnt    *int64  `gorm:"column:seat_cnt" json:"seat_cnt"`
	UseYn      *string `gorm:"column:use_yn" json:"use_yn"`
	UseMin     *int64  `gorm:"column:use_min" json:"use_min"`
	MinCnt     *int64  `gorm:"column:min_cnt" json:"min_cnt"`
	ReserveDay *int64  `gorm:"column:reserve_day" json:"reserve_day"`
	ReserveMin *int64  `gorm:"column:reserve_min" json:"reserve_min"`
	CancelMin  *int64  `gorm:"column:cancel_min" json:"cancel_min"`
	BlockYn    *string `gorm:"column:block_yn" json:"block_yn"`
	BlockMin   *int64  `gorm:"column:block_min" json:"block_min"`
	ContYn     *string `gorm:"column:cont_yn" json:"cont_yn"`
	ContMin    *int64  `gorm:"column:cont_min" json:"cont_min"`
	EtcUseYn   *string `gorm:"column:etc_use_yn" json:"etc_use_yn"`
	EtcName    *string `gorm:"column:etc_name" json:"etc_name"`
	Bigo       *string `gorm:"column:bigo" json:"bigo"`
}

// TableName WiseDroom's table name
func (*WiseDroom) TableName() string {
	return TableNameWiseDroom
}
